/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedShoppingListsRouteImport } from './routes/_authenticated.shopping-lists'
import { Route as AuthenticatedSpecialsRouteImport } from './routes/_authenticated.specials'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated.history.index'
import { Route as AuthenticatedHistoryTripIdRouteImport } from './routes/_authenticated.history.$tripId'
import { Route as AuthenticatedShoppingListsIndexRouteImport } from './routes/_authenticated.shopping-lists.index'
import { Route as AuthenticatedShoppingListsListIdRouteImport } from './routes/_authenticated.shopping-lists.$listId'
import { Route as AuthenticatedShoppingListsListIdShopRouteImport } from './routes/_authenticated.shopping-lists.$listId.shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShoppingListsRoute =
  AuthenticatedShoppingListsRouteImport.update({
    id: '/shopping-lists',
    path: '/shopping-lists',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpecialsRoute = AuthenticatedSpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)
const AuthenticatedHistoryTripIdRoute =
  AuthenticatedHistoryTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)
const AuthenticatedShoppingListsIndexRoute =
  AuthenticatedShoppingListsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShoppingListsRoute,
  } as any)
const AuthenticatedShoppingListsListIdRoute =
  AuthenticatedShoppingListsListIdRouteImport.update({
    id: '/$listId',
    path: '/$listId',
    getParentRoute: () => AuthenticatedShoppingListsRoute,
  } as any)
const AuthenticatedShoppingListsListIdShopRoute =
  AuthenticatedShoppingListsListIdShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => AuthenticatedShoppingListsListIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shopping-lists': typeof AuthenticatedShoppingListsRouteWithChildren
  '/specials': typeof AuthenticatedSpecialsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/history/$tripId': typeof AuthenticatedHistoryTripIdRoute
  '/shopping-lists/$listId': typeof AuthenticatedShoppingListsListIdRouteWithChildren
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/shopping-lists/': typeof AuthenticatedShoppingListsIndexRoute
  '/shopping-lists/$listId/shop': typeof AuthenticatedShoppingListsListIdShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/specials': typeof AuthenticatedSpecialsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/history/$tripId': typeof AuthenticatedHistoryTripIdRoute
  '/shopping-lists/$listId': typeof AuthenticatedShoppingListsListIdRouteWithChildren
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/shopping-lists': typeof AuthenticatedShoppingListsIndexRoute
  '/shopping-lists/$listId/shop': typeof AuthenticatedShoppingListsListIdShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shopping-lists': typeof AuthenticatedShoppingListsRouteWithChildren
  '/_authenticated/specials': typeof AuthenticatedSpecialsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/history/$tripId': typeof AuthenticatedHistoryTripIdRoute
  '/_authenticated/shopping-lists/$listId': typeof AuthenticatedShoppingListsListIdRouteWithChildren
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/shopping-lists/': typeof AuthenticatedShoppingListsIndexRoute
  '/_authenticated/shopping-lists/$listId/shop': typeof AuthenticatedShoppingListsListIdShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/settings'
    | '/shopping-lists'
    | '/specials'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/history/$tripId'
    | '/shopping-lists/$listId'
    | '/history/'
    | '/shopping-lists/'
    | '/shopping-lists/$listId/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/specials'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/history/$tripId'
    | '/shopping-lists/$listId'
    | '/history'
    | '/shopping-lists'
    | '/shopping-lists/$listId/shop'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/shopping-lists'
    | '/_authenticated/specials'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/history/$tripId'
    | '/_authenticated/shopping-lists/$listId'
    | '/_authenticated/history/'
    | '/_authenticated/shopping-lists/'
    | '/_authenticated/shopping-lists/$listId/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping-lists': {
      id: '/_authenticated/shopping-lists'
      path: '/shopping-lists'
      fullPath: '/shopping-lists'
      preLoaderRoute: typeof AuthenticatedShoppingListsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/specials': {
      id: '/_authenticated/specials'
      path: '/specials'
      fullPath: '/specials'
      preLoaderRoute: typeof AuthenticatedSpecialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/history/$tripId': {
      id: '/_authenticated/history/$tripId'
      path: '/$tripId'
      fullPath: '/history/$tripId'
      preLoaderRoute: typeof AuthenticatedHistoryTripIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/shopping-lists/': {
      id: '/_authenticated/shopping-lists/'
      path: '/'
      fullPath: '/shopping-lists/'
      preLoaderRoute: typeof AuthenticatedShoppingListsIndexRouteImport
      parentRoute: typeof AuthenticatedShoppingListsRoute
    }
    '/_authenticated/shopping-lists/$listId': {
      id: '/_authenticated/shopping-lists/$listId'
      path: '/$listId'
      fullPath: '/shopping-lists/$listId'
      preLoaderRoute: typeof AuthenticatedShoppingListsListIdRouteImport
      parentRoute: typeof AuthenticatedShoppingListsRoute
    }
    '/_authenticated/shopping-lists/$listId/shop': {
      id: '/_authenticated/shopping-lists/$listId/shop'
      path: '/shop'
      fullPath: '/shopping-lists/$listId/shop'
      preLoaderRoute: typeof AuthenticatedShoppingListsListIdShopRouteImport
      parentRoute: typeof AuthenticatedShoppingListsListIdRoute
    }
  }
}

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryTripIdRoute: typeof AuthenticatedHistoryTripIdRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryTripIdRoute: AuthenticatedHistoryTripIdRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedShoppingListsListIdRouteChildren {
  AuthenticatedShoppingListsListIdShopRoute: typeof AuthenticatedShoppingListsListIdShopRoute
}

const AuthenticatedShoppingListsListIdRouteChildren: AuthenticatedShoppingListsListIdRouteChildren =
  {
    AuthenticatedShoppingListsListIdShopRoute:
      AuthenticatedShoppingListsListIdShopRoute,
  }

const AuthenticatedShoppingListsListIdRouteWithChildren =
  AuthenticatedShoppingListsListIdRoute._addFileChildren(
    AuthenticatedShoppingListsListIdRouteChildren,
  )

interface AuthenticatedShoppingListsRouteChildren {
  AuthenticatedShoppingListsListIdRoute: typeof AuthenticatedShoppingListsListIdRouteWithChildren
  AuthenticatedShoppingListsIndexRoute: typeof AuthenticatedShoppingListsIndexRoute
}

const AuthenticatedShoppingListsRouteChildren: AuthenticatedShoppingListsRouteChildren =
  {
    AuthenticatedShoppingListsListIdRoute:
      AuthenticatedShoppingListsListIdRouteWithChildren,
    AuthenticatedShoppingListsIndexRoute: AuthenticatedShoppingListsIndexRoute,
  }

const AuthenticatedShoppingListsRouteWithChildren =
  AuthenticatedShoppingListsRoute._addFileChildren(
    AuthenticatedShoppingListsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShoppingListsRoute: typeof AuthenticatedShoppingListsRouteWithChildren
  AuthenticatedSpecialsRoute: typeof AuthenticatedSpecialsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShoppingListsRoute: AuthenticatedShoppingListsRouteWithChildren,
  AuthenticatedSpecialsRoute: AuthenticatedSpecialsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
